/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTracksRouteImport } from './routes/app.tracks'
import { Route as AppTeamRouteImport } from './routes/app.team'
import { Route as AppTracksTrackIdRouteImport } from './routes/app.tracks.$trackId'
import { Route as AppModulesModuleIdRouteImport } from './routes/app.modules.$moduleId'
import { Route as AppLearnTrackIdRouteImport } from './routes/app.learn.$trackId'
import { Route as AppLearnTrackIdModuleIdRouteImport } from './routes/app.learn.$trackId.$moduleId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTracksRoute = AppTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppTracksTrackIdRoute = AppTracksTrackIdRouteImport.update({
  id: '/$trackId',
  path: '/$trackId',
  getParentRoute: () => AppTracksRoute,
} as any)
const AppModulesModuleIdRoute = AppModulesModuleIdRouteImport.update({
  id: '/modules/$moduleId',
  path: '/modules/$moduleId',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnTrackIdRoute = AppLearnTrackIdRouteImport.update({
  id: '/learn/$trackId',
  path: '/learn/$trackId',
  getParentRoute: () => AppRoute,
} as any)
const AppLearnTrackIdModuleIdRoute = AppLearnTrackIdModuleIdRouteImport.update({
  id: '/$moduleId',
  path: '/$moduleId',
  getParentRoute: () => AppLearnTrackIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/team': typeof AppTeamRoute
  '/app/tracks': typeof AppTracksRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/learn/$trackId': typeof AppLearnTrackIdRouteWithChildren
  '/app/modules/$moduleId': typeof AppModulesModuleIdRoute
  '/app/tracks/$trackId': typeof AppTracksTrackIdRoute
  '/app/learn/$trackId/$moduleId': typeof AppLearnTrackIdModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/team': typeof AppTeamRoute
  '/app/tracks': typeof AppTracksRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/learn/$trackId': typeof AppLearnTrackIdRouteWithChildren
  '/app/modules/$moduleId': typeof AppModulesModuleIdRoute
  '/app/tracks/$trackId': typeof AppTracksTrackIdRoute
  '/app/learn/$trackId/$moduleId': typeof AppLearnTrackIdModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/team': typeof AppTeamRoute
  '/app/tracks': typeof AppTracksRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/learn/$trackId': typeof AppLearnTrackIdRouteWithChildren
  '/app/modules/$moduleId': typeof AppModulesModuleIdRoute
  '/app/tracks/$trackId': typeof AppTracksTrackIdRoute
  '/app/learn/$trackId/$moduleId': typeof AppLearnTrackIdModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/team'
    | '/app/tracks'
    | '/app/'
    | '/app/learn/$trackId'
    | '/app/modules/$moduleId'
    | '/app/tracks/$trackId'
    | '/app/learn/$trackId/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/team'
    | '/app/tracks'
    | '/app'
    | '/app/learn/$trackId'
    | '/app/modules/$moduleId'
    | '/app/tracks/$trackId'
    | '/app/learn/$trackId/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/team'
    | '/app/tracks'
    | '/app/'
    | '/app/learn/$trackId'
    | '/app/modules/$moduleId'
    | '/app/tracks/$trackId'
    | '/app/learn/$trackId/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tracks': {
      id: '/app/tracks'
      path: '/tracks'
      fullPath: '/app/tracks'
      preLoaderRoute: typeof AppTracksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/team': {
      id: '/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tracks/$trackId': {
      id: '/app/tracks/$trackId'
      path: '/$trackId'
      fullPath: '/app/tracks/$trackId'
      preLoaderRoute: typeof AppTracksTrackIdRouteImport
      parentRoute: typeof AppTracksRoute
    }
    '/app/modules/$moduleId': {
      id: '/app/modules/$moduleId'
      path: '/modules/$moduleId'
      fullPath: '/app/modules/$moduleId'
      preLoaderRoute: typeof AppModulesModuleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/learn/$trackId': {
      id: '/app/learn/$trackId'
      path: '/learn/$trackId'
      fullPath: '/app/learn/$trackId'
      preLoaderRoute: typeof AppLearnTrackIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/learn/$trackId/$moduleId': {
      id: '/app/learn/$trackId/$moduleId'
      path: '/$moduleId'
      fullPath: '/app/learn/$trackId/$moduleId'
      preLoaderRoute: typeof AppLearnTrackIdModuleIdRouteImport
      parentRoute: typeof AppLearnTrackIdRoute
    }
  }
}

interface AppTracksRouteChildren {
  AppTracksTrackIdRoute: typeof AppTracksTrackIdRoute
}

const AppTracksRouteChildren: AppTracksRouteChildren = {
  AppTracksTrackIdRoute: AppTracksTrackIdRoute,
}

const AppTracksRouteWithChildren = AppTracksRoute._addFileChildren(
  AppTracksRouteChildren,
)

interface AppLearnTrackIdRouteChildren {
  AppLearnTrackIdModuleIdRoute: typeof AppLearnTrackIdModuleIdRoute
}

const AppLearnTrackIdRouteChildren: AppLearnTrackIdRouteChildren = {
  AppLearnTrackIdModuleIdRoute: AppLearnTrackIdModuleIdRoute,
}

const AppLearnTrackIdRouteWithChildren = AppLearnTrackIdRoute._addFileChildren(
  AppLearnTrackIdRouteChildren,
)

interface AppRouteChildren {
  AppTeamRoute: typeof AppTeamRoute
  AppTracksRoute: typeof AppTracksRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppLearnTrackIdRoute: typeof AppLearnTrackIdRouteWithChildren
  AppModulesModuleIdRoute: typeof AppModulesModuleIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppTeamRoute: AppTeamRoute,
  AppTracksRoute: AppTracksRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppLearnTrackIdRoute: AppLearnTrackIdRouteWithChildren,
  AppModulesModuleIdRoute: AppModulesModuleIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
